services:
  mysql:
    image: mysql:8.2
    container_name: mysql8-container
    restart: no
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: jht
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: demo
    volumes:
      - ./mysql_data:/var/lib/mysql
