server:
  port: 8090
management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      group:
#        /actuator/health/custom
        custom:
          include: "my"
  health:
    defaults:
      enabled: true
  trace:
    http:
      enabled: true
  metrics:
    export:
      simple:
        enabled: true
    web:
      server:
        request:
#          /actuator/metrics/http.server.requests
          metric-name: "http.server.requests"
#      include:

# 配置应用信息 /actuator/info
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"
