DROP TABLE IF EXISTS t_user;

create table t_user
(
    id          bigint generated by default as identity,
    create_by   bigint,
    create_time timestamp,
    modify_by   bigint,
    modify_time timestamp,
    age         integer,
    email       varchar(255),
    name        varchar(50) not null,
    primary key (id)
);