
server:
  servlet:
    encoding:
      enabled: true
      # 已为默认
      charset: utf-8
      force: true


logging:
  level:
    web: debug
#    org.springframework.web.filter.GenericFilterBean: debug