server:
  servlet:
    encoding:
      enabled: true
      # 已为默认
      charset: utf-8
      force: true


logging:
  level:
    web: debug
    com.xiaodao.filter.contentcache.CachingRequestLogFilter: debug
    org.springframework.boot.web.servlet.ServletContextInitializerBeans: trace
#    org.springframework.web.filter.GenericFilterBean: debug