spring:
  datasource:
    username: SS_DIFF
    password: SS_DIFF
    url: jdbc:dm://127.0.0.1:5236/TEST?schema=TEST&STU&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    driver-class-name: dm.jdbc.driver.DmDriver
    hikari:
      pool-name: "jht-pool"
      maximum-pool-size: 109
      max-lifetime: 600009
      idle-timeout: 300009
      minimum-idle: 19
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DmDialect
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.DmDialect
