spring:
  rabbitmq:
    addresses: 127.0.0.1:5672,127.0.0.1:5673,127.0.0.1:5674
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: "2s"
